importScripts('xweb-info.js'); // generated by live/build.js: XWEB = { styles, version }

// x-web harness, live mode (dev extension).
//
// Toolbar button on a logged-in x.com tab:
//   off -> on : read what x-web needs through the classic app (page/collect.js),
//               hold back the classic app's scripts and x-web's own network for
//               this tab, reload, and boot x-web's real client (page/boot.js)
//   on -> off : drop the rules and reload: the classic app is back.
// The block/mute extension keeps running in the tab as usual.

const STATE_KEY = (tabId) => 'live:' + tabId;
const RULE_BASE = 9000;
const PAGE_LIB = ['page/resolver.js', 'page/classic-adapter.js', 'page/reader.js', 'page/xweb-graph.js'];

async function getState(tabId) {
  const k = STATE_KEY(tabId);
  return (await chrome.storage.session.get(k))[k] || null;
}

// Per-tab rules. Ids are derived from the tab id so they can be removed again.
function rulesFor(tabId) {
  const base = RULE_BASE + (tabId % 100000) * 4;
  return [
    // the classic app (responsive-web): x-web takes the page instead
    { id: base, priority: 1, action: { type: 'block' }, condition: { tabIds: [tabId], urlFilter: '||abs.twimg.com/responsive-web/', resourceTypes: ['script'] } },
    // x-web's own API and telemetry (its GraphQL is answered in the page), and the
    // Google/Apple sign-in SDKs its logged-out frame loads: nothing of x-web goes out
    { id: base + 1, priority: 1, action: { type: 'block' }, condition: { tabIds: [tabId], requestDomains: ['api.x.com', 'api.twitter.com', 'sentry.io', 'accounts.google.com', 'appleid.cdn-apple.com'] } },
  ];
}

async function setRules(tabId, on) {
  const rules = rulesFor(tabId);
  await chrome.declarativeNetRequest.updateSessionRules({
    removeRuleIds: rules.map((r) => r.id),
    addRules: on ? rules : [],
  });
}

async function enter(tabId) {
  await chrome.scripting.executeScript({ target: { tabId }, world: 'MAIN', files: ['page/classic-adapter.js', 'page/reader.js'] });
  const [res] = await chrome.scripting.executeScript({ target: { tabId }, world: 'MAIN', files: ['page/collect.js'] });
  const data = res && res.result;
  if (!data || !data.model || !data.model.viewerId) throw new Error('not a logged-in x.com tab (or the classic app is not loaded)');
  await chrome.storage.session.set({ [STATE_KEY(tabId)]: data });
  await setRules(tabId, true);
  await chrome.action.setBadgeText({ tabId, text: 'XW' });
  await chrome.tabs.reload(tabId);
}

async function exit(tabId) {
  await chrome.storage.session.remove(STATE_KEY(tabId));
  await setRules(tabId, false);
  await chrome.action.setBadgeText({ tabId, text: '' });
  await chrome.tabs.reload(tabId);
}

async function toggle(tabId) {
  if (await getState(tabId)) return exit(tabId);
  return enter(tabId);
}

// Boot x-web as soon as a live tab starts loading.
chrome.tabs.onUpdated.addListener(async (tabId, info, tab) => {
  if (info.status !== 'loading' || !/^https:\/\/x\.com\//.test(tab.url || '')) return;
  const data = await getState(tabId);
  if (!data) return;
  const urls = {
    entry: chrome.runtime.getURL('xweb/xwh-entry.js'),
    css: chrome.runtime.getURL('xweb/assets/' + XWEB.styles),
    version: XWEB.version,
  };
  try {
    await chrome.scripting.executeScript({ target: { tabId }, world: 'MAIN', injectImmediately: true, files: PAGE_LIB.concat(['page/boot.js']) });
    await chrome.scripting.executeScript({ target: { tabId }, world: 'MAIN', injectImmediately: true, func: (d, u) => window.xwhBoot(d, u), args: [data, urls] });
  } catch (err) {
    console.warn('[xweb-harness] boot failed', err);
  }
});

chrome.tabs.onRemoved.addListener((tabId) => {
  chrome.storage.session.remove(STATE_KEY(tabId));
  setRules(tabId, false);
});

chrome.action.onClicked.addListener((tab) => {
  if (!tab.id || !/^https:\/\/x\.com\//.test(tab.url || '')) return;
  toggle(tab.id).catch((err) => {
    console.warn('[xweb-harness]', err);
    chrome.action.setBadgeText({ tabId: tab.id, text: 'ERR' });
    chrome.action.setTitle({ tabId: tab.id, title: 'x-web harness: ' + err.message });
  });
});

// for live/selftest.js
self.xwhToggle = toggle;
